[package]
name = "muxtls-proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Wire protocol definitions and codec for muxtls"
repository.workspace = true
homepage.workspace = true
readme = "../README.md"
keywords = ["network", "protocol"]
categories = ["network-programming"]
license.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
